DROP TABLE users IF EXISTS;
DROP TABLE user_platforms IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    telegram_id     VARCHAR(255)                 NOT NULL,
    membership_id   VARCHAR(255)                 NOT NULL,
    nickname        VARCHAR(255)            NOT NULL,
    mebmership_type INTEGER                 NOT NULL,
    registered      TIMESTAMP DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX user_telegram_id ON users (telegram_id);

CREATE TABLE user_platforms
(
    user_id  INTEGER NOT NULL,
    platform VARCHAR(20),
    CONSTRAINT user_platforms_idx UNIQUE (user_id, platform),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
)

